--
-- Dump do projeto Gestão de Pedidos
--
-- Executar conectado ao banco padrão "postgres" (não é preciso criar um banco novo).
-- Este script cria:
--   * o schema gestao_pedidos
--   * as tabelas usuario, cliente, endereco, produto, pedido e produto_pedido
--     (com chaves primárias, estrangeiras e sequências de id)
--   * os dados de exemplo (usuário, clientes, produtos e pedidos)
--
-- Uso: psql -h localhost -U postgres -d postgres -f dump_gestao_pedidos.sql
--
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: gestao_pedidos; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA gestao_pedidos;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cliente; Type: TABLE; Schema: gestao_pedidos; Owner: -
--

CREATE TABLE gestao_pedidos.cliente (
    id integer NOT NULL,
    ativo boolean,
    cnpj character varying(14),
    email character varying(150),
    exige_nota_fiscal boolean,
    nome character varying(100) NOT NULL,
    telefone character varying(11),
    endereco_id integer NOT NULL,
    usuario_id integer NOT NULL
);


--
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE gestao_pedidos.cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gestao_pedidos.cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: endereco; Type: TABLE; Schema: gestao_pedidos; Owner: -
--

CREATE TABLE gestao_pedidos.endereco (
    id integer NOT NULL,
    bairro character varying(255) NOT NULL,
    cep character varying(8) NOT NULL,
    cidade character varying(255) NOT NULL,
    estado character varying(50) NOT NULL,
    numero integer NOT NULL,
    rua character varying(255) NOT NULL
);


--
-- Name: endereco_id_seq; Type: SEQUENCE; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE gestao_pedidos.endereco ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gestao_pedidos.endereco_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido; Type: TABLE; Schema: gestao_pedidos; Owner: -
--

CREATE TABLE gestao_pedidos.pedido (
    id integer NOT NULL,
    data date NOT NULL,
    valor_total numeric(10,2),
    cliente_id integer NOT NULL,
    usuario_id integer NOT NULL
);


--
-- Name: pedido_id_seq; Type: SEQUENCE; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE gestao_pedidos.pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gestao_pedidos.pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produto; Type: TABLE; Schema: gestao_pedidos; Owner: -
--

CREATE TABLE gestao_pedidos.produto (
    id integer NOT NULL,
    ativo boolean,
    nome character varying(100) NOT NULL,
    valor_base numeric(10,2) NOT NULL,
    usuario_id integer NOT NULL
);


--
-- Name: produto_id_seq; Type: SEQUENCE; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE gestao_pedidos.produto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gestao_pedidos.produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produto_pedido; Type: TABLE; Schema: gestao_pedidos; Owner: -
--

CREATE TABLE gestao_pedidos.produto_pedido (
    id integer NOT NULL,
    quantidade integer NOT NULL,
    valor_unitario numeric(10,2) NOT NULL,
    pedido_id integer NOT NULL,
    produto_id integer NOT NULL
);


--
-- Name: produto_pedido_id_seq; Type: SEQUENCE; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE gestao_pedidos.produto_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gestao_pedidos.produto_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: gestao_pedidos; Owner: -
--

CREATE TABLE gestao_pedidos.usuario (
    id integer NOT NULL,
    email character varying(150) NOT NULL,
    nome character varying(100) NOT NULL,
    senha character varying(255) NOT NULL
);


--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE gestao_pedidos.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gestao_pedidos.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cliente; Type: TABLE DATA; Schema: gestao_pedidos; Owner: -
--

INSERT INTO gestao_pedidos.cliente VALUES (3, true, '19600133000127', 'astralchapeco@hotmail.com', true, 'CH COMERCIO DE UTILIDADES LTDA', '4733820431', 3, 2);
INSERT INTO gestao_pedidos.cliente VALUES (4, true, '89083863000183', 'contato@cncomercio.com.br', true, 'CN COMERCIO DE UTILIDADES LTDA', '4732214900', 4, 2);
INSERT INTO gestao_pedidos.cliente VALUES (5, true, '79402654000100', 'bazarjcs2@gmail.com', true, 'COMERCIAL COSTA E SILVA LTDA', '4733221845', 5, 2);
INSERT INTO gestao_pedidos.cliente VALUES (6, true, '23511615000188', 'lojaoastrallages@yahoo.com.br', true, 'COMERCIAL MCD LTDA EEP', '4932233227', 6, 2);
INSERT INTO gestao_pedidos.cliente VALUES (2, true, '10433218000193', 'financeiro.timbo@lojaoastral.com.br', false, 'CDC COMERCIO DE UTILIDADES LTDA', '47991599517', 2, 2);
INSERT INTO gestao_pedidos.cliente VALUES (7, true, '59407816000187', 'financeiro@emporioastral.com.br', false, 'EMPORIO ASTRAL UTILIDADES LTDA', '4736342278', 7, 2);


--
-- Data for Name: endereco; Type: TABLE DATA; Schema: gestao_pedidos; Owner: -
--

INSERT INTO gestao_pedidos.endereco VALUES (1, 'Morro do Meio', '89215230', 'Joinville', 'Santa Catarina', 1, 'Rua Alior Alves de Lima');
INSERT INTO gestao_pedidos.endereco VALUES (2, 'Centro', '89120000', 'Timbó', 'SC', 1250, 'Rua Germano Brandes');
INSERT INTO gestao_pedidos.endereco VALUES (3, 'Centro', '89802000', 'Chapecó', 'SC', 870, 'Avenida Getúlio Dorneles Vargas');
INSERT INTO gestao_pedidos.endereco VALUES (4, 'Centro', '89201600', 'Joinville', 'SC', 540, 'Rua XV de Novembro');
INSERT INTO gestao_pedidos.endereco VALUES (6, 'Centro', '88502000', 'Lages', 'SC', 315, 'Rua Coronel Córdova');
INSERT INTO gestao_pedidos.endereco VALUES (7, 'Centro', '89251600', 'Jaraguá do Sul', 'SC', 460, 'Rua Reinoldo Rau');
INSERT INTO gestao_pedidos.endereco VALUES (5, 'Costa e Silva', '89010201', 'Joinville', 'SC', 1320, 'Rua Sete de Setembro');


--
-- Data for Name: pedido; Type: TABLE DATA; Schema: gestao_pedidos; Owner: -
--

INSERT INTO gestao_pedidos.pedido VALUES (1, '2026-06-05', 450.00, 3, 2);
INSERT INTO gestao_pedidos.pedido VALUES (2, '2026-08-07', 400.00, 7, 2);
INSERT INTO gestao_pedidos.pedido VALUES (3, '2026-07-23', 1100.00, 2, 2);
INSERT INTO gestao_pedidos.pedido VALUES (4, '2026-09-10', 1080.00, 5, 2);
INSERT INTO gestao_pedidos.pedido VALUES (6, '2026-09-25', 490.00, 7, 2);


--
-- Data for Name: produto; Type: TABLE DATA; Schema: gestao_pedidos; Owner: -
--

INSERT INTO gestao_pedidos.produto VALUES (4, true, 'ENFEITE DE PORTA', 4.00, 2);
INSERT INTO gestao_pedidos.produto VALUES (5, true, 'ESTOJO NECESSAIRE TAM G', 22.00, 2);
INSERT INTO gestao_pedidos.produto VALUES (6, true, 'PORTA TERÇO (chaveiro)', 10.00, 2);
INSERT INTO gestao_pedidos.produto VALUES (12, true, 'PESO FERRADURA', 9.00, 2);
INSERT INTO gestao_pedidos.produto VALUES (15, true, 'PESOS DE PORTA SAQUINHO GR', 11.00, 2);
INSERT INTO gestao_pedidos.produto VALUES (16, true, 'protetor de porta 80cm', 15.00, 2);
INSERT INTO gestao_pedidos.produto VALUES (18, true, 'ESTOJO NECESSAIRE TAM P', 18.00, 2);
INSERT INTO gestao_pedidos.produto VALUES (19, true, 'PESO DE PORTA QUADRADO(SUBLIMADO)', 4.20, 2);
INSERT INTO gestao_pedidos.produto VALUES (3, true, 'ALMOCHAVEIRO', 7.00, 2);
INSERT INTO gestao_pedidos.produto VALUES (21, true, 'ESTOJO NECESSAIRE TAM M', 20.00, 2);


--
-- Data for Name: produto_pedido; Type: TABLE DATA; Schema: gestao_pedidos; Owner: -
--

INSERT INTO gestao_pedidos.produto_pedido VALUES (1, 20, 20.00, 1, 18);
INSERT INTO gestao_pedidos.produto_pedido VALUES (2, 10, 5.00, 1, 4);
INSERT INTO gestao_pedidos.produto_pedido VALUES (3, 10, 22.00, 2, 5);
INSERT INTO gestao_pedidos.produto_pedido VALUES (4, 10, 18.00, 2, 18);
INSERT INTO gestao_pedidos.produto_pedido VALUES (5, 100, 11.00, 3, 15);
INSERT INTO gestao_pedidos.produto_pedido VALUES (6, 60, 18.00, 4, 18);
INSERT INTO gestao_pedidos.produto_pedido VALUES (9, 10, 22.00, 6, 21);
INSERT INTO gestao_pedidos.produto_pedido VALUES (10, 15, 18.00, 6, 18);


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: gestao_pedidos; Owner: -
--

INSERT INTO gestao_pedidos.usuario VALUES (2, 'teste@gmail.com', 'Teste', '$2a$10$mnnEurrF6nYn4GjEg6n7Rebm6IRzBl3LduZQ9yzUWSLcMgacsCHES');


--
-- Name: cliente_id_seq; Type: SEQUENCE SET; Schema: gestao_pedidos; Owner: -
--

SELECT pg_catalog.setval('gestao_pedidos.cliente_id_seq', 9, true);


--
-- Name: endereco_id_seq; Type: SEQUENCE SET; Schema: gestao_pedidos; Owner: -
--

SELECT pg_catalog.setval('gestao_pedidos.endereco_id_seq', 9, true);


--
-- Name: pedido_id_seq; Type: SEQUENCE SET; Schema: gestao_pedidos; Owner: -
--

SELECT pg_catalog.setval('gestao_pedidos.pedido_id_seq', 6, true);


--
-- Name: produto_id_seq; Type: SEQUENCE SET; Schema: gestao_pedidos; Owner: -
--

SELECT pg_catalog.setval('gestao_pedidos.produto_id_seq', 21, true);


--
-- Name: produto_pedido_id_seq; Type: SEQUENCE SET; Schema: gestao_pedidos; Owner: -
--

SELECT pg_catalog.setval('gestao_pedidos.produto_pedido_id_seq', 10, true);


--
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: gestao_pedidos; Owner: -
--

SELECT pg_catalog.setval('gestao_pedidos.usuario_id_seq', 2, true);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- Name: endereco endereco_pkey; Type: CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.endereco
    ADD CONSTRAINT endereco_pkey PRIMARY KEY (id);


--
-- Name: pedido pedido_pkey; Type: CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.pedido
    ADD CONSTRAINT pedido_pkey PRIMARY KEY (id);


--
-- Name: produto_pedido produto_pedido_pkey; Type: CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.produto_pedido
    ADD CONSTRAINT produto_pedido_pkey PRIMARY KEY (id);


--
-- Name: produto produto_pkey; Type: CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.produto
    ADD CONSTRAINT produto_pkey PRIMARY KEY (id);


--
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);


--
-- Name: cliente uk7v21uy9djyl7hh9464kkjsjg0; Type: CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.cliente
    ADD CONSTRAINT uk7v21uy9djyl7hh9464kkjsjg0 UNIQUE (endereco_id);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- Name: pedido fk30s8j2ktpay6of18lbyqn3632; Type: FK CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.pedido
    ADD CONSTRAINT fk30s8j2ktpay6of18lbyqn3632 FOREIGN KEY (cliente_id) REFERENCES gestao_pedidos.cliente(id);


--
-- Name: produto fk4qqkq7cmomd87obw16prilngw; Type: FK CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.produto
    ADD CONSTRAINT fk4qqkq7cmomd87obw16prilngw FOREIGN KEY (usuario_id) REFERENCES gestao_pedidos.usuario(id);


--
-- Name: cliente fk64nr9yt889by5lufr1boo5i4s; Type: FK CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.cliente
    ADD CONSTRAINT fk64nr9yt889by5lufr1boo5i4s FOREIGN KEY (endereco_id) REFERENCES gestao_pedidos.endereco(id);


--
-- Name: pedido fk6uxomgomm93vg965o8brugt00; Type: FK CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.pedido
    ADD CONSTRAINT fk6uxomgomm93vg965o8brugt00 FOREIGN KEY (usuario_id) REFERENCES gestao_pedidos.usuario(id);


--
-- Name: produto_pedido fk7sii2gvnu51osdh2f9qrmxxas; Type: FK CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.produto_pedido
    ADD CONSTRAINT fk7sii2gvnu51osdh2f9qrmxxas FOREIGN KEY (produto_id) REFERENCES gestao_pedidos.produto(id);


--
-- Name: produto_pedido fkawsdcony69c35yvelg8e8kkr7; Type: FK CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.produto_pedido
    ADD CONSTRAINT fkawsdcony69c35yvelg8e8kkr7 FOREIGN KEY (pedido_id) REFERENCES gestao_pedidos.pedido(id);


--
-- Name: cliente fkc3u631ocxdrtm3ccpme0kjlmu; Type: FK CONSTRAINT; Schema: gestao_pedidos; Owner: -
--

ALTER TABLE ONLY gestao_pedidos.cliente
    ADD CONSTRAINT fkc3u631ocxdrtm3ccpme0kjlmu FOREIGN KEY (usuario_id) REFERENCES gestao_pedidos.usuario(id);


--
-- PostgreSQL database dump complete
--


